version: 2.1

setup: true

parameters:
  scheduled:
    type: boolean
    default: false

orbs: 
  path-filtering: circleci/path-filtering@0.1.1
  continuation: circleci/continuation@0.2.0

jobs:
  filter-paths:
    docker:
      - image: cimg/base:stable
    steps:   
      - checkout
      - path-filtering/set-parameters:
          base-revision: main
          mapping: |
            scripts/.*  skip-run  true
          output-path: /tmp/pipeline-parameters.json
      - run:
          name: Set up scheduled parameter
          command: |
            cat /tmp/pipeline-parameters.json | jq '. + {scheduled: << pipeline.parameters.scheduled >>}'   

workflows:
  choose-config:
    jobs:
      - filter-paths