version: 2.1

setup: true

parameters:
  scheduled:
    type: boolean
    default: false

orbs: 
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  choose-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            scripts/.*  skip-run  true
            *           scheduled << pipeline.parameters.scheduled >>